"""initial db

Revision ID: 500e2f52cf35
Revises: 
Create Date: 2018-04-29 06:25:02.148738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500e2f52cf35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
